server:
  port: 9095
#  servlet:
#    context-path: /demo
spring:
  #  profiles:
  #    active: h2
  thymeleaf:
    cache: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/static/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: jf1224
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  global-config:
    # 关闭banner
    banner: false
dcs:
  aes:
    secret:
      key: 2095132720951327
      iv: 6075877187097700
  jwt:
    expired-seconds: 86400000
  shiro:
    white-list:
      - /
      - /favicon.*
      - /static/**
      - /index**
      - /plugin
      - /platform/**
      - /websocket
      - /configs/**
      - /shenyu-client/**
      - /error
      - /actuator/health
      - /swagger-ui.html
      - /webjars/**
      - /swagger-resources/**
      - /v2/api-docs
      - /csrf
